### ISSUE TITLE
roi_crop no attribute error

### ISSUE THREAD

**Issue by j777shin** [luwr1022/listwise-view-ranking#2]
```
Traceback (most recent call last):
  File "demo.py", line 111, in <module>
    best_anchor = evaluate_single_image(img, pdefined_anchors, model, args)
  File "demo.py", line 77, in evaluate_single_image
    scores = model(img, rois)
  File "/home/rachel/anaconda3/envs/lvr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rachel/Projects/image-data/listwise-view-ranking/lib/model/LVRN.py", line 44, in forward
    f = self.RoI_op.RoIRefine(f, rois)
  File "/home/rachel/Projects/image-data/listwise-view-ranking/lib/model/RoI_operation.py", line 55, in RoIRefine
    pooled_features = self.roi_crop(featrues, grid_yx.detach())
  File "/home/rachel/anaconda3/envs/lvr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rachel/Projects/image-data/listwise-view-ranking/lib/model/roi_crop/modules/roi_crop.py", line 8, in forward
    return RoICropFunction()(input1, input2)
  File "/home/rachel/Projects/image-data/listwise-view-ranking/lib/model/roi_crop/functions/roi_crop.py", line 14, in forward
    roi_crop.BilinearSamplerBHWD_updateOutput_cuda(input1, input2, output)
AttributeError: module 'model.roi_crop._ext.roi_crop' has no attribute 'BilinearSamplerBHWD_updateOutput_cuda'
```

this is my error when i tried to run demo.py
I downloaded model and put one image under ./images
could you help me with this?

**Comment by luwr1022** [comment]
The function'BilinearSamplerBHWD_updateOutput_cuda' is declared in './roi_crop/src/roi_crop_cuda.h' and definited in './roi_crop/src/roi_crop_cuda.c'.

If the roi_crop(roi_align, roi_pooling modules) are built successfully in the third step, we will get '_roi_crop.so' in './roi_crop/_ext/roi_crop'.

Required for successful build: Pytorch0.4('torch.utils.ffi' is deprecated in Pytorch1.0+), CUDA and CUDNN.

NOTE: In 'make.sh', the CUDA is specified as 8.0 and you need to confirm if it is consistent with your environment.

**Comment by luwr1022** [comment]
The function'BilinearSamplerBHWD_updateOutput_cuda' is declared in './roi_crop/src/roi_crop_cuda.h' and definited in './roi_crop/src/roi_crop_cuda.c'.

If the roi_crop(roi_align, roi_pooling modules) are built successfully in the third step, we will get '_roi_crop.so' in './roi_crop/_ext/roi_crop'.

Required for successful build: Pytorch0.4('torch.utils.ffi' is deprecated in Pytorch1.0+), CUDA and CUDNN.

NOTE: In 'make.sh', the CUDA is specified as 8.0 and you need to confirm if it is consistent with your environment.
